export const PartnerData = [
  {
    id: 1,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 2,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 3,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 4,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 5,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 6,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 7,
    title: "Civilworks",
    type: "Engenharia",
    image: "/remarkable/assets/Parceiros/civilworks.jpg",
  },
  {
    id: 8,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 9,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 10,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 11,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 12,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 13,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
  {
    id: 14,
    title: "Flávio Magalhães Fisioterapeuta",
    type: "Saúde",
    image: "/remarkable/assets/Parceiros/flavio.jpg",
  },
];
