import civilworks from "../../assets/Parceiros/civilworks.jpg";
import flavio from "../../assets/Parceiros/flavio.jpg";
import farmotive from "../../assets/Parceiros/farmotive.jpg";
import tisoauto from "../../assets/Parceiros/tisoauto.jpg";
import emilia from "../../assets/Parceiros/emilia.jpg";
import novum from "../../assets/Parceiros/novum.jpg";
import carlosSeabra from "../../assets/Parceiros/carlosSeabra.jpg";
import oceanPace from "../../assets/Parceiros/oceanPace.jpg";
import routeFilms from "../../assets/Parceiros/routeFilms.jpg";
import sandraTeixeira from "../../assets/Parceiros/sandraTeixeira.jpg";

export const PartnerData = [
  {
    id: 1,
    title: "Civilworks",
    description:
      "A CivilWorks assume-se como uma empresa de Engenharia e Consultoria.",
    type: "Engenharia",
    image: civilworks,
    to_email: "mmagalhaes@civilworks.pt",
    services: [
      "Trabalhos de Consultoria na Área de Engenharia",
      "Peritagens e Vistorias",
      "Engenharia Forense",
      "Fiscalizações de Obra",
      "Gestão Contratual de Projetos",
      "Avaliação Imobiliária",
      "Análise de propostas de Empreitadas",
      "Projetos de Especialidades",
      "Execução de Empreitadas",
    ],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 2,
    title: "Tisoauto",
    type: "Setor Automóvel",
    description:
      "Mais do que um fornecedor, um parceiro da sua oficina. A Tisoauto tem uma visão 360º para os seus clientes profissionais. Empresa dedicada à venda exclusiva de Peças de Automóveis para clientes Profissionais.",
    image: tisoauto,
    to_email: "ruimoreira@tisoauto.pt",
    services: [
      "Distribuição",
      "Formação",
      "Apoio Técnico",
      "Planos de Fidelização",
      "Ferramentas para oficinas",
      "Ferramentas de diagnóstico",
    ],
    address: "",
    addressLink: "",
    phone: "255 310 230",
  },
  {
    id: 3,
    title: "Farmotive",
    description:
      "A Farmotive assume-se como uma oficina Multimarcas especializada no grupo VAG.",
    type: "Setor Automóvel",
    image: farmotive,
    to_email: "geral@farmotive.pt",
    services: [
      "Manutenção Oficial",
      "Mecatrónica",
      "Pneus e Alinhamento",
      "Serviço de Pré-Inspeção",
      "Lavagens",
    ],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 4,
    title: "Flávio Magalhães",
    description: "Fisioterapeuta",
    type: "Saúde",
    image: flavio,
    to_email: "fisioflaviomagalhaes@gmail.com",
    services: [
      "Fisioterapia Espcializada",
      "Performance Desportiva e Reabilitação",
      "Fisioterapia Músculo Esquelética",
      "Eletropuntura",
      "Osteopatia",
      "Fisioterapia Invasiva",
      "Reeducação Postural Global",
      "Massagens",
    ],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 5,
    title: "Emilia Maia",
    description: "Advogada",
    type: "Advocacia",
    image: emilia,
    to_email: "emiliammaia-50850P@adv.oa.pt",
    services: ["Advocacia", "Consultoria Júridica"],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 6,
    title: "Carlos Seabra",
    type: "Contabilidade",
    description: "Contabilista",
    image: carlosSeabra,
    to_email: "geral@cscontabilidade.pt",
    services: ["Contabilidade", "Consultoria", "Jurisdição", "Portugal2030"],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 7,
    title: "Novum Canal",
    description: "",
    type: "Media",
    image: novum,
    to_email: "geral@novumcanal.pt",
    services: [
      "Cobertura de Eventos",
      "Publireportagens",
      "Inauguração de Espaços",
      "Cartões de Publicidade",
    ],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 8,
    title: "Route Films",
    description: "",
    type: "Media",
    image: routeFilms,
    to_email: "routefilmspt@gmail.com",
    services: ["Cinemamatografia", "Audivisuais", "Fotografia", "Design"],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 9,
    title: "Ocean Pace",
    description: "",
    type: "Media",
    image: oceanPace,
    to_email: "geral@oceanpacevisuals.pt",
    services: [
      "Vídeo e Fotografia para Eventos",
      "Videoclipes Musicais",
      "Cobertura de Casamentos e Batizados",
    ],
    address: "",
    addressLink: "",
    phone: "",
  },
  {
    id: 10,
    title: "Sandra Teixeira",
    description: "Advogada",
    type: "Advocacia",
    image: sandraTeixeira,
    to_email: "sandratgomes-10909p@adv.oa.pt",
    services: ["Advocacia", "Consultoria Júridica"],
    address: "",
    addressLink: "",
    phone: "",
  },
];
